-- ScholarshipOS seed data: 24 sample scholarships
-- Run after 001_initial_schema.sql

insert into public.scholarships
  (title, provider, amount, deadline, description, eligibility_summary, min_gpa, interests, zip_scope, url)
values
  ('Coca-Cola Scholars Program',
   'Coca-Cola Scholars Foundation',
   20000,
   '2026-10-31',
   'Achievement-based scholarship for high school seniors demonstrating leadership, service, and academic excellence.',
   'U.S. high school senior; min 3.0 GPA; demonstrated leadership and service.',
   3.00, array['leadership','community service'], 'national',
   'https://www.coca-colascholarsfoundation.org/apply/'),

  ('Gates Scholarship',
   'Bill & Melinda Gates Foundation',
   50000,
   '2026-09-15',
   'Full cost-of-attendance scholarship for high-achieving, low-income minority students.',
   'Pell-eligible; minority background; min 3.3 GPA; strong leadership.',
   3.30, array['leadership','academics','stem'], 'national',
   'https://www.thegatesscholarship.org/scholarship'),

  ('Dell Scholars Program',
   'Michael & Susan Dell Foundation',
   20000,
   '2026-12-01',
   'Supports students who have overcome significant obstacles to pursue a college education.',
   'Min 2.4 GPA; participating college readiness program; financial need.',
   2.40, array['grit','first-generation'], 'national',
   'https://www.dellscholars.org/scholarship/'),

  ('Jack Kent Cooke Foundation College Scholarship',
   'Jack Kent Cooke Foundation',
   55000,
   '2026-11-18',
   'For high-achieving high school seniors with financial need attending four-year colleges.',
   'Min 3.5 GPA; family income under $95k; top of class.',
   3.50, array['academics','leadership'], 'national',
   'https://www.jkcf.org/our-scholarships/college-scholarship-program/'),

  ('Horatio Alger National Scholarship',
   'Horatio Alger Association',
   25000,
   '2026-10-25',
   'For students who have faced and overcome great obstacles in their young lives.',
   'Min 2.0 GPA; family income under $55k; demonstrated integrity and perseverance.',
   2.00, array['grit','community service'], 'national',
   'https://scholars.horatioalger.org/scholarships/'),

  ('Ron Brown Scholar Program',
   'Ron Brown Scholar Fund',
   40000,
   '2026-11-01',
   'Scholarship for African-American high school seniors demonstrating academic excellence and leadership.',
   'African-American high school senior; min 3.0 GPA; significant financial need.',
   3.00, array['leadership','academics','community service'], 'national',
   'https://www.ronbrown.org/apply/the-ron-brown-scholarship/'),

  ('QuestBridge National College Match',
   'QuestBridge',
   60000,
   '2026-09-27',
   'Matches high-achieving, low-income students with full four-year scholarships to top colleges.',
   'High school senior; family income under $65k; strong academic record.',
   3.50, array['academics','first-generation'], 'national',
   'https://www.questbridge.org/high-school-students/national-college-match'),

  ('Society of Women Engineers Scholarship',
   'Society of Women Engineers',
   15000,
   '2026-05-01',
   'Supports women pursuing ABET-accredited bachelor or graduate student programs in engineering.',
   'Identify as female; pursuing engineering/CS; min 3.5 GPA.',
   3.50, array['stem','engineering'], 'national',
   'https://swe.org/scholarships/'),

  ('AXA Achievement Scholarship',
   'AXA Foundation',
   10000,
   '2026-12-15',
   'Recognizes students who demonstrate ambition, drive, determination and the ability to succeed.',
   'U.S. high school senior; min 2.5 GPA; ambition and drive.',
   2.50, array['leadership','grit'], 'national',
   'https://us.axa.com/axa-foundation/axa-achievement-scholarship.html'),

  ('Elks National Foundation Most Valuable Student',
   'Elks National Foundation',
   50000,
   '2026-11-13',
   'Four-year scholarships for high school seniors based on leadership, financial need, and scholarship.',
   'U.S. high school senior; need-based; leadership in school/community.',
   3.00, array['leadership','community service'], 'national',
   'https://www.elks.org/scholars/scholarships/mvs.cfm'),

  ('Burger King Scholars',
   'Burger King McLamore Foundation',
   50000,
   '2026-12-15',
   'Awards for graduating high school seniors with financial need and strong work ethic.',
   'Min 2.5 GPA; work experience a plus; financial need.',
   2.50, array['grit'], 'national',
   'https://bkmclamorefoundation.org/programs/burger-king-scholars/'),

  ('Davidson Fellows Scholarship',
   'Davidson Institute',
   50000,
   '2026-02-12',
   'For students 18 and under who have completed a significant piece of work in STEM or philosophy.',
   'Under 18; significant independent work in STEM, lit, music, or philosophy.',
   null, array['stem','research'], 'national',
   'https://www.davidsongifted.org/gifted-programs/fellows-scholarship/'),

  ('Regeneron Science Talent Search',
   'Society for Science',
   250000,
   '2026-11-10',
   'Nations most prestigious science and math competition for high school seniors.',
   'U.S. high school senior; original STEM research project.',
   null, array['stem','research'], 'national',
   'https://www.societyforscience.org/regeneron-sts/'),

  ('National Merit Scholarship',
   'National Merit Scholarship Corporation',
   2500,
   '2026-10-01',
   'Awarded to high scorers on the PSAT/NMSQT taken in junior year.',
   'U.S. high school junior who took PSAT/NMSQT; top ~1% scorer.',
   3.50, array['academics'], 'national',
   'https://www.nationalmerit.org/s/1758/start.aspx'),

  ('Hispanic Scholarship Fund',
   'HSF',
   5000,
   '2026-02-15',
   'Scholarships for students of Hispanic heritage pursuing higher education.',
   'Hispanic heritage; min 3.0 GPA; U.S. citizen or eligible non-citizen.',
   3.00, array['academics','first-generation'], 'national',
   'https://www.hsf.net/scholarship'),

  ('American Indian College Fund Full Circle Scholarship',
   'American Indian College Fund',
   5000,
   '2026-05-31',
   'Supports Native American students enrolled in accredited U.S. institutions.',
   'Enrolled member of federally recognized tribe; min 2.0 GPA.',
   2.00, array['community service'], 'national',
   'https://collegefund.org/students/scholarships/'),

  ('Point Foundation Scholarship',
   'Point Foundation',
   12000,
   '2026-01-28',
   'Empowers promising LGBTQ students to achieve their full academic and leadership potential.',
   'LGBTQ identifying; leadership potential; academic achievement.',
   3.20, array['leadership','community service'], 'national',
   'https://pointfoundation.org/point-apply/apply-now/'),

  ('San Francisco Foundation Community Scholarship',
   'San Francisco Foundation',
   5000,
   '2026-03-15',
   'For Bay Area high school seniors demonstrating financial need and civic engagement.',
   'Bay Area resident; high school senior; financial need.',
   2.50, array['community service','leadership'], 'zip:94110',
   'https://sff.org/scholarships/'),

  ('Silicon Valley Community Foundation Scholarship',
   'SVCF',
   3000,
   '2026-04-01',
   'Awards for South Bay students pursuing four-year degrees.',
   'Santa Clara / San Mateo County resident; demonstrated need.',
   2.75, array['academics','community service'], 'zip:94301',
   'https://www.siliconvalleycf.org/scholarships'),

  ('Rotary Club District 5170 Scholarship',
   'Rotary International',
   2500,
   '2026-03-31',
   'Local Rotary club scholarship for Bay Area graduating seniors with service orientation.',
   'Bay Area resident; service hours; min 3.0 GPA.',
   3.00, array['community service','leadership'], 'zip:94110',
   'https://rotary5170.org/scholarships'),

  ('Peninsula Community Foundation Scholarship',
   'Peninsula Community Foundation',
   4000,
   '2026-02-28',
   'For San Mateo County students pursuing vocational or four-year programs.',
   'San Mateo County high school senior; financial need.',
   2.80, array['grit','first-generation'], 'zip:94010',
   'https://www.peninsulacf.org/scholarships'),

  ('Kaiser Permanente Hippocrates Circle Scholarship',
   'Kaiser Permanente',
   5000,
   '2026-04-15',
   'Supports students from underrepresented backgrounds pursuing careers in medicine.',
   'Min 3.0 GPA; interest in healthcare/medicine; underrepresented in medicine.',
   3.00, array['stem','healthcare','first-generation'], 'national',
   'https://about.kaiserpermanente.org/community-health/partnerships/hippocrates-circle'),

  ('National Society of High School Scholars Scholarship',
   'NSHSS',
   2000,
   '2026-10-15',
   'Various scholarships for NSHSS members demonstrating academic excellence.',
   'NSHSS member; min 3.5 GPA; varies by scholarship.',
   3.50, array['academics','leadership'], 'national',
   'https://www.nshss.org/scholarships/'),

  ('VFW Voice of Democracy Scholarship',
   'Veterans of Foreign Wars',
   35000,
   '2026-10-31',
   'Audio-essay competition open to high school students on a patriotic theme.',
   'Grades 9-12 in U.S.; submit 3-5 minute audio essay.',
   null, array['writing','leadership'], 'national',
   'https://www.vfw.org/community/youth-and-education/youth-scholarships');
